### ISSUE TITLE
LoadDeviceStateFromFileEx関数を追加してみてはいかがでしょうか？

### ISSUE THREAD

**Issue by m-ito348** [a-nemoto313/video-capture-for-tiscam#4]
LoadDeviceStateFromFileEx(_grabber, tis.T(file))関数を使用することで、設定されたファイルを読み込みカメラを切り替えることが可能。
~~カメラを閉じてから再度LoadDeviceStateFromFile()を実行するより処理速度が速いメリットがある。~~

**Comment by a-nemoto313** [comment]
#10 で実装済み
