### ISSUE TITLE
requirements.txtに記載されているMyVideoCaptureは、pip install -r requirements.txtではインストールできない。

### ISSUE THREAD

**Issue by m-ito348** [a-nemoto313/video-capture-for-tiscam#6]
pip freeze > requirements.txtで出力したrequirements.txtに記載されているMyVideoCaptureは、pip install -r requirements.txtでインストールできない問題。

**Comment by a-nemoto313** [comment]
リポジトリをパブリックにしたことで解消されたはず。
`pip install git+https://github.com/a-nemoto313/video-capture-for-tiscam.git`でインストール、
`pip freeze > requirements.txt`すると、下記のようなファイルが作成され、
```
...
MyVideoCapture @ git+https://github.com/a-nemoto313/video-capture-for-tiscam.git@0f94ea2bdffe6ca8c5e213e9f47e2dcfa2530d16
...
```
他の環境で`pip install -r requirements.txt`するとちゃんとインストールできるはず。

後ろの`...@0f94ea2bdffe6ca8c5e213e9f47e2dcfa2530d16`が鬱陶しいが、
コミットのID（ハッシュ）を表していて、`opencv-python==4.5.5.64`の"==4.5.5.64"みたいなもの。
もし`@0f94ea2bdffe6ca8c5e213e9f47e2dcfa2530d16`を消しても`pip install -r requirements.txt`できるが、
その場合は最新のバージョンがインストールされる。
ただ、当然`pip freeze > requirements.txt`したタイミング以降にバージョンアップが行われていた場合はそれぞれの環境でバージョンが変わってしまうことになるので、残しておくべき。
